worker_processes 1;

daemon off;
error_log logs/error.log warn;
pid logs/nginx.pid;

events {
    worker_connections 1024;
}

http {

    resolver 8.8.8.8; # 구글 DNS

    include       mime.types;
    default_type  application/octet-stream;

    lua_code_cache on;
    lua_package_path "/usr/local/openresty/luajit-rocks/share/lua/5.1/?.lua;$prefix/src/?.lua;;";

    client_body_timeout 5s; # 요청 바디 수신 타임아웃
    client_header_timeout 5s; # 요청 헤더 수신 타임아웃

    # upstream backend {
    #     server http://backend:8080;
    #     keepalive 64;
    # }

    init_by_lua_file src/init.lua;


    server {
        listen 80;

        include conf.d/*.conf;

        location / {
            proxy_redirect http://localhost:8080/ /;
            proxy_redirect http://ec2-xx-xx.compute.amazonaws.com:8080/ /;

            proxy_pass http://backend:8080;

            port_in_redirect off;
        }
    }
}